{% set name = "PICor" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MolecularBioinformatics/PICor/archive/v{{ version }}.tar.gz
  sha256: 931f39e48012bbb8a03b510afdf88dee7d56a71d1d35d4f0445cd38e6b87e2ac

build:
  entry_points:
    - picor = picor.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pyscaffold >=3.2a0,<3.3a0
    - pip
  run:
    - python >=3.6
    - pandas
    - scipy
    - docopt
    - openpyxl

test:
  imports:
    - picor
  commands:
    - pip check
    - picor --help
  requires:
    - pip

about:
  home: https://github.com/MolecularBioinformatics/PICor
  summary: Python package for correcting mass spectrometry data for the effect of natural isotope abundance
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Danzelot
